Storm.InterviewTest.Hearthstone/Controllers/CardController.cs
using System.Web.Mvc;
using Storm.InterviewTest.Hearthstone.Core.Features.Cards.Services;

namespace Storm.InterviewTest.Hearthstone.Controllers
{
	public class CardController : Controller
	{
		public ActionResult Details(string id)
		{
			var searchService = new CardSearchService(MvcApplication.CardCache);

			var model = searchService.FindById(id);

			return View(model);
		}
	}
}

Storm.InterviewTest.Hearthstone/Controllers/CardsController.cs
using System.Web.Mvc;
using Storm.InterviewTest.Hearthstone.Core.Features.Cards.Services;

namespace Storm.InterviewTest.Hearthstone.Controllers
{
    public class CardsController : Controller
    {
		public ActionResult Index(string q = null)
		{
			var searchService = new CardSearchService(MvcApplication.CardCache);
			var cards = searchService.Search(q);

			return View(cards);
		}
	}
}

Storm.InterviewTest.Hearthstone/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Storm.InterviewTest.Hearthstone.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

Storm.InterviewTest.Hearthstone/Controllers/MediaController.cs
using System.IO;
using System.Net;
using System.Web.Mvc;

namespace Storm.InterviewTest.Hearthstone.Controllers
{
    public class MediaController : Controller
    {
	    private const string mediaSourceUrl = "http://wow.zamimg.com/images/hearthstone/cards/enus/medium/{0}.png";

        // GET: Media
        public ActionResult Card(string id)
        {
	        var cardFilename = string.Format("{0}.png", id);
	        var localBaseDirectory = Server.MapPath("~/App_Data/media/");
	        Directory.CreateDirectory(localBaseDirectory);
	        var localFile = Path.Combine(localBaseDirectory, cardFilename);
	        if (!System.IO.File.Exists(localFile))
	        {
		        DownloadFromSource(id, localFile);
	        }

			return File(localFile, "image/png");
		}

	    private void DownloadFromSource(string cardId, string localFile) {
		    var client = new WebClient();
			client.DownloadFile(string.Format(mediaSourceUrl, cardId), localFile);
	    }
    }
}

Storm.InterviewTest.Hearthstone/Controllers/MyDecksController.cs
using System.Web.Mvc;
using Storm.InterviewTest.Hearthstone.Core.Features.Cards.Services;

namespace Storm.InterviewTest.Hearthstone.Controllers
{
	public class MyDecksController : Controller
	{
		public ActionResult Index()
		{
			var searchService = new CardSearchService(MvcApplication.CardCache);
			var heroes = searchService.GetHeroes();
			return View(heroes);
		}
	}
}

Storm.InterviewTest.Hearthstone/Views/Card/Details.cshtml
@model Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models.CardModel

@{
    ViewBag.Title = "title";
}

@Html.DisplayForModel()



Storm.InterviewTest.Hearthstone/Views/Cards/Index.cshtml
@model IEnumerable<Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models.CardModel>
@{
    ViewBag.Title = "Home Page";
}

<div class="page-header">
    <h2>Cards (Total: @Model.Count())</h2>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="row" style="margin-bottom: 10px">
            <div class="col-md-12">
                <form class="form-inline" method="GET">
                    <input class="form-control" type="search" name="q" id="q" value="" placeholder="search for cards..." />
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>    
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ul class="list-inline">
                    @foreach (var card in Model)
                    {
                        <li class="list-group-item">
                            @{ Html.RenderPartial("_card", card); }
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

Storm.InterviewTest.Hearthstone/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Hearthstone: Heroes of Warcraft</h1>
    <p>This is the Hearthstone: Heroes of Warcraft Card Browser and Deck Builder</p>
    <p><a class="btn btn-primary btn-lg" href="@Url.Action("Index", "Cards")" role="button">Browse Cards...</a></p>
    <p class="text-center">
        <iframe width="560" height="315" src="//www.youtube.com/embed/2S0XO-X9Q2c" frameborder="0" allowfullscreen></iframe>
    </p>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Task 1: Understand the code</div>
    <div class="panel-body">
        <p>Run, debug and investigate the web application in order that you given understanding of the functionality of the site.</p>
        <p>The unit tests are written using the Storm test context specification which is a wrapper over the popular NUnit testing library, the nunit adapter is installed via nuget and should allow the unit tests to be executed within Visual Studio.</p>
        <ul>
            <li>Can you list the design patterns in use within the web application?</li>
            <li>Would you introduce any new patterns/practices or change any of the existing patterns/practices?</li>
        </ul>
        <p>We can discuss these points at the interview</p>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Task 2a: Bug Report</div>
    <div class="panel-body">
        <p>We have received the following bug report from a user:</p>
        <p>
            <pre>Hi,
I am trying to use the website to build my super mage deck, when i browse the cards and search for mage specific cards using the keyword 'mage' I only see 3?  surely there are more mage specific class cards than that, where is <strong>Fireball</strong> and <strong>Arcane Explosion</strong>?
           </pre>
        </p>
        <p>Investigate the bug report and if you discover any issues correct them and also implement any additional supporting tests that ensure that the issue is detected before a release in future.</p>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Task 2b: Change Request</div>
    <div class="panel-body">
        <p>A lot of people are searching for cards by <code>PlayerClass</code>, unfortunately the search box can at times return results that are not just for that <code>PlayerClass</code>.</p>
        <p>We have been tasked with improving the card search so that the user can select a player class from a dropdown list positioned before the search box, this will allow them to filter the cards by the selected <code>PlayerClass</code> with the option of also using the search box to refine the results even further</p>
        <p>The dropdown list should default to an option that searches all <code>PlayerClass</code> types</p>
        <img src="~/Content/images/search_options.png"/>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Task 2c: Additional Change Request</div>
    <div class="panel-body">
        <p>Currently the 9 hero classes are also shown on the card browser, these cards should not be shown within the card browser</p>
        <p>e.g. The <code>Priest</code> hero card called "Anduin Wrynn"</p>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Task 3: Add a Display Template for the <code>Rarity</code> property within the <code>CardModel</code> model class</div>
    <div class="panel-body">
        <p>Whenever the <code>Rarity</code> property is displayed within a view across the whole site it should have custom formatting encapsulated within a Display Template.</p>
        <p>The following layout is expected for each value:</p>
        <ul class="list-unstyled">
            <li><strong style="color: silver;"><abbr title="Free Card">Free</abbr></strong></li>
            <li><strong style="color: slategray;"><abbr title="Common Card">Common</abbr></strong></li>
            <li><strong style="color: blue;"><abbr title="Rare Card">Rare</abbr></strong></li>
            <li><strong style="color: blueviolet;"><abbr title="Epic Card">Epic</abbr></strong></li>
            <li><strong style="color: coral;"><abbr title="Ohhhh shiny, shiny!">Legendary</abbr></strong></li>
        </ul>

    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Task 4: Refactor the MediaController</div>
    <div class="panel-body">
        <p>The MediaController was introduced to allow individual card images to cached on first use, however the implementation is not testable.</p>
        <p>Refactor the action method within the MediaController, you should look to do the following:
        <ol>
            <li>Implement a reusable service class/component for retrieving checking, downloading and returning a path to a media image</li>
            <li>Add unit tests to the solution that verify the success and error conditions of the service class</li>
        </ol>
        <div class="alert alert-info">Hint: Look at the existing services for examples</div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Task 5: Review and refactor the <code>LocalJsonFeedHearthstoneCardCacheFactory</code> service class</div>
    <div class="panel-body">
        <p>Refactor the service class to improve maintainability and reduce cyclomatic complexity</p>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Task 6: Refactor the card browser view</div>
    <div class="panel-body">
        <p>Refactor the card browsing page to use a partial view to show card list, allowing it to be reused on other pages to display any list of cards (i.e. listing the cards within a custom deck)</p>
    </div>
</div>
<div class="panel panel-default panel-danger">
    <div class="panel-heading">Task 7: Adjust the Front End Build Process</div>
    <div class="panel-body">
        <p>Currently the project uses the <pre>Microsoft.AspNet.Web.Optimization</pre> package and NuGet packages to manage the front-end dependencies and build process. Adjust this to use a more appropriate front-end package manager and build system (pick your favourite!)</p>
    </div>
    <div class="panel-footer">This is an extra task - don't worry if you don't have time to implement this.</div>
</div>
<div class="panel panel-default panel-danger">
    <div class="panel-heading">Task 8: Make the Cards page able to show cards by Rarity or cards by Player Class</div>
    <div class="panel-body">
        <p>Currently the Player Class and Rarity labels are not clickable. Make it so that it's possible to see only cards in a particular Player Class or of a particular rarity on the page. You can do this either on the front-end or the back-end - be prepared to justify your choice.</p>
    </div>
</div>
<div class="panel panel-default panel-danger">
    <div class="panel-heading">Task 9: Search for visual bugs</div>
    <div class="panel-body">
        <p>At certain breakpoints, there are some visual bugs contained within the site. Sweep the site to find as many of these as possible and fix what you can.</p>
    </div>
</div>
<div class="panel panel-default panel-danger">
    <div class="panel-heading">Task 10: Add paging functionality<i class="pull-right glyphicon glyphicon-exclamation-sign"></i></div>
    <div class="panel-body">
        <p>Currently the card browser lists all cards on a single page, add the ability to page through the cards in groups of 25</p>
    </div>
    <div class="panel-footer">This is an extra task, dont worry if you dont have time to implement this, it is here if you wish to give it a go and impress us :)</div>
</div>
<div class="panel panel-default panel-danger">
    <div class="panel-heading">Task 999: Clear the desk, clear my schedule...</div>
    <div class="panel-body">
        <a class="btn btn-danger" href="@Url.Action("Index", "MyDecks")"><i class="glyphicon glyphicon-fire"></i> I'm going in....</a>
    </div>
    <div class="panel-footer">
        <p>This is an extra task, and involves reading and implementing a set of requirements to add an additional feature to the application.</p>
        <p>This is really a task aimed at a senior/experienced developer so again, dont worry about completing this, have a read through the spec and we might ask you how you would consider going about implementing this.</p>
    </div>
</div>

Storm.InterviewTest.Hearthstone/Views/MyDecks/Index.cshtml
@model IEnumerable<Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models.CardModel>
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Deck Builder</h1>
    <p>Coming soon....maybe?</p>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Up for a challenge?</div>
    <div class="panel-body">
        <p>The deck builder is designed to allow users to create custom decks of cards</p>
        <ul>
            <li>A deck is created for one of the following heroes:
                <ul class="list-inline">
                    @foreach (var hero in Model)
                    {
                        <li>@{ Html.RenderPartial("_Card", hero); }</li>
                    }
                </ul>
            </li>
            <li>A deck can only contain neutral cards a neutral card has a null <code>PlayerClass</code>, or cards with a <code>PlayerClass</code> that matches that chosen hero for the deck.</li>
            <li>A deck must be given a name, this is supplied by the user</li>
            <li>A deck must contain exactly <strong>30</strong> cards</li>
            <li>A deck can only contain cards of type <code>Minion</code>, <code>Spell</code>, <code>Weapon</code></li>
            <li>A deck can contain to up 2 copies of the same card</li>
            <li>Any specific card can only exist once per deck if it has a <code>Rarity</code> of <strong style="color: blueviolet">Epic</strong> or <strong style="color: coral">Legendary</strong>.</li>
        </ul>
    </div>
</div>

Storm.InterviewTest.Hearthstone/Views/Shared/DisplayTemplates/HeroModel.cshtml
@model Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models.HeroModel

<div class="panel panel-default">
    <div class="row">
        <div class="col-md-3">
            @{ Html.RenderPartial("_Card", Model); }
        </div>
        <div class="col-md-9">
            <form class="form-horizontal">
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Name)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Name)" />
                </div>
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Type)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Type)" />
                </div>
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Rarity)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Rarity)" />
                </div>                            
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Faction)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Faction)" />
                </div>
            </form>
        </div>
    </div>
    <div class="panel panel-footer">
        @Html.ActionLink("Back to Cards", "Index", "Cards")
    </div>
</div>

Storm.InterviewTest.Hearthstone/Views/Shared/DisplayTemplates/MinionModel.cshtml
@model Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models.MinionModel

<div class="panel panel-default">
    <div class="row">
        <div class="col-md-3">
            @{ Html.RenderPartial("_Card", Model); }
        </div>
        <div class="col-md-9">
            <form class="form-horizontal">
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Name)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Name)" />
                </div>
                @if (Model.PlayerClass != null)
                {
                    Html.RenderPartial("_Card", Model.PlayerClass);
                }
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Type)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Type)" />
                </div>
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Rarity)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Rarity)" />
                </div>                            
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Faction)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Faction)" />
                </div>
            </form>
        </div>
    </div>
    <div class="panel panel-footer">
        @Html.ActionLink("Back to Cards", "Index", "Cards")
    </div>
</div>

Storm.InterviewTest.Hearthstone/Views/Shared/DisplayTemplates/SpellModel.cshtml
@model Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models.SpellModel

<div class="panel panel-default">
    <div class="row">
        <div class="col-md-3">
            @{ Html.RenderPartial("_Card", Model); }
        </div>
        <div class="col-md-9">
            <form class="form-horizontal">
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Name)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Name)" />
                </div>
                @if (Model.PlayerClass != null)
                {
                    Html.RenderPartial("_Card", Model.PlayerClass);
                }
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Type)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Type)" />
                </div>
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Rarity)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Rarity)" />
                </div>                            
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Faction)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Faction)" />
                </div>
            </form>
        </div>
    </div>
    <div class="panel panel-footer">
        @Html.ActionLink("Back to Cards", "Index", "Cards")
    </div>
</div>

Storm.InterviewTest.Hearthstone/Views/Shared/DisplayTemplates/WeaponModel.cshtml
@model Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models.WeaponModel

<div class="panel panel-default">
    <div class="row">
        <div class="col-md-3">
            @{ Html.RenderPartial("_Card", Model); }
        </div>
        <div class="col-md-9">
            <form class="form-horizontal">
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Name)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Name)" />
                </div>
                @if (Model.PlayerClass != null)
                {
                    Html.RenderPartial("_Card", Model.PlayerClass);
                }
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Type)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Type)" />
                </div>
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Rarity)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Rarity)" />
                </div>                            
                <div class="form-group">
                    <label class="form-control-static">@Html.DisplayNameFor(model => model.Faction)</label>
                    <input type="text" readonly="readonly" class="form-control" value="@Html.DisplayFor(model => model.Faction)" />
                </div>
            </form>
        </div>
    </div>
    <div class="panel panel-footer">
        @Html.ActionLink("Back to Cards", "Index", "Cards")
    </div>
</div>

Storm.InterviewTest.Hearthstone/Views/Shared/_Card.cshtml
@model Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models.CardModel

<div class="row">
    <div class="col-md-12">
        <a href="@Url.Action("Details", "Card", new { id = Model.Id })"><img class="img-responsive img-thumbnail" src="@Model.ImageUrl" alt="@Model.Name" title="@Model.Name" /></a>        
    </div>
    <div class="col-md-12 text-center">
        <span class="label label-default">@Model.PlayerClassText</span>
    </div>
</div>

Storm.InterviewTest.Hearthstone/Views/Shared/_Layout.cshtml
@using System.Reflection
<!DOCTYPE html>
@{
    var version = string.Empty;
    var versionAttrib = typeof (MvcApplication).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
    if (versionAttrib != null)
    {
        version = versionAttrib.InformationalVersion;
    }
}

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/images/hearthstone.png" height="50" class="pull-left"/>
                @Html.ActionLink("Hearthstone Deck Creator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Card Browser", "Index", "Cards")</li>
                    <li>@Html.ActionLink("My Decks", "Index", "MyDecks")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="pull-left">&copy; Images are copyright of Blizzard Entertainment</p>
            <p class="pull-right">v@(version)</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>